# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "server.vagrant"
    config.vm.network "private_network", ip: "192.168.42.10"
    config.vm.provision "shell" do |shell|
        shell.path = "scripts/bootstrap.sh"
    end
    # Use VBoxManage to customize the VM. For example to change memory:
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
end
